site_name: RT Thread Workshop MUICT 2025
site_url: https://thaicodeorg.github.io/rt-thread-workshop/
theme:
  logo: assets/logo.png
  name: material
  palette:
    primary: teal
  font:
    text: IBM Plex Sans Thai Looped
  features:
    - navigation.top
    - navigation.footer
    - content.code.copy
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


copyright: Copyright &copy; 2025 Sawangpong muadphet <sawangpongm@gmail.com>